version: "3.9"
services:
  resolve-buddy-db:
    image: postgres
    restart: always
    container_name: resolve-buddy-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: satyajit
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
